### registration
POST localhost:8080/api/auth/verification/1
Accept-Language: UZ
Content-Type: application/json

{
  "name": "Javohir",
  "surname": "Yallayev",
  "username": "adminjon",
  "password": "123",
  "birthdate": "2001-06-12",
  "profession": "Dasturchi",
  "team": true,
  "region": "Samarkand",
  "district": "Pastdargom",
  "phoneHome": "+998997684433"
}

###
GET localhost:8080/api/auth/public/login
Accept-Language: UZ
Content-Type: application/json

{
  "username": "adminjon",
  "password": "1234"
}



###
GET https://a.nel.cloudflare.com/report/v3?s=fBtUH50muHn62jeLYrnRjh8CjYdg8H2f2dBpLO3I612zuqYf7N2piXX%2BFRgRoAyoCTCmjy914zVmOEY7hAmH3U2uk7SwteBqeoeqaQWpVdmAr1pTXPIaEX7kOJ9%2BEG5P